--SQL PARA SELECIONAR TODOS OS DADOS DA TABELA ESTOQUE
select * from tblEstoque


--SQL PARA SELECIONAR ALGUNS CALCULOS DA TABELA ESTOQUE
SELECT
	count(TBLESTOQUE.ID_PRODUTO) as 'ITENS CADASTRADOS NO ESTOQUE',
	sum(FLTVALORCUSTOUNITARIO)* sum(INTQUANTIDADEENTRADA) - sum(INTQUANTIDADEVENDIDA) as 'CUSTO TOTAL DO ESTOQUE',
	sum(FLTVALORVENDAUNITARIO)* sum(INTQUANTIDADEENTRADA) - sum(INTQUANTIDADEVENDIDA) as 'VALOR VENDA TOTAL ESTOQUE',
	min(DTEENTRADA) as 'DATA DE ENTRADA DO PRIMEIRO PRODUTO',
	max(DTEENTRADA) as 'DATA DE ENTRADA DO ULTIMO PRODUTO',
	sum(INTQUANTIDADEENTRADA) as 'TOTAL DE PRODUTOS DE ENTRADA',
	sum(INTQUANTIDADEVENDIDA) as 'TOTAL DE PRODUTOS VENDIDOS',
	(sum(INTQUANTIDADEENTRADA)) - (sum(INTQUANTIDADEVENDIDA)) as 'QUANTIDADE EXISTENTE EM ESTOQUE',
	sum(FLTVALORVENDAUNITARIO)* sum(INTQUANTIDADEENTRADA) - sum(INTQUANTIDADEVENDIDA) - sum(FLTVALORCUSTOUNITARIO)* sum(INTQUANTIDADEENTRADA) - sum(INTQUANTIDADEVENDIDA) as 'LUCRO TOTAL DO ESTOQUE'
from TBLESTOQUE

--SQL PARA SELECIONAR DADOS DE TODOS OS PRODUTOS CADASTRADOS + DADOS DE CALCULOS DE ESTOQUE
SELECT        
(SELECT
	count(TBLESTOQUE.ID_PRODUTO) as 'ITENS CADASTRADOS NO ESTOQUE' FROM TBLESTOQUE) AS 'ITENS CADASTRADOS NO ESTOQUE',
(SELECT
	sum(FLTVALORCUSTOUNITARIO)* sum(INTQUANTIDADEENTRADA) - sum(INTQUANTIDADEVENDIDA)FROM TBLESTOQUE) as 'CUSTO TOTAL DO ESTOQUE',
(SELECT
	sum(FLTVALORVENDAUNITARIO)* sum(INTQUANTIDADEENTRADA) - sum(INTQUANTIDADEVENDIDA)FROM TBLESTOQUE) as 'VALOR VENDA TOTAL ESTOQUE',
(SELECT
	min(DTEENTRADA)FROM TBLESTOQUE) as 'DATA DE ENTRADA DO PRIMEIRO PRODUTO',
(SELECT
	max(DTEENTRADA)FROM TBLESTOQUE) as 'DATA DE ENTRADA DO ULTIMO PRODUTO',
(SELECT
	sum(INTQUANTIDADEENTRADA)FROM TBLESTOQUE) as 'TOTAL DE PRODUTOS DE ENTRADA',
(SELECT
	sum(INTQUANTIDADEVENDIDA)FROM TBLESTOQUE) as 'TOTAL DE PRODUTOS VENDIDOS',
(SELECT
	(sum(INTQUANTIDADEENTRADA)) - (sum(INTQUANTIDADEVENDIDA))FROM TBLESTOQUE) as 'QUANTIDADE DE PRODUTOS EXISTENTES EM ESTOQUE',
(SELECT
	sum(FLTVALORVENDAUNITARIO)* sum(INTQUANTIDADEENTRADA) - sum(INTQUANTIDADEVENDIDA) - sum(FLTVALORCUSTOUNITARIO)* sum(INTQUANTIDADEENTRADA) - sum(INTQUANTIDADEVENDIDA)FROM TBLESTOQUE) as 'LUCRO TOTAL DO ESTOQUE',
TBLPRODUTO.ID_PRODUTO AS 'ID DO PRODUTO', TBLESTOQUE.DTEENTRADA AS 'ENTRADA ESTOQUE', 
                         TBLESTOQUE.FLTVALORCUSTOUNITARIO AS 'CUSTO UNITARIO', TBLTIPOPRODUTO.STRNOME AS 'TIPO DO PRODUTO', 
                         TBLREVENDEDOR.STRNOME AS REVENDEDOR, TBLREVENDEDOR.STREMAIL AS 'E-MAIL DO REVENDEDOR', 
                         TBLREVENDEDOR.STRCELULAR AS 'CELULAR DO REVENDEDOR', TBLREVENDEDOR.STRTELEFONE AS 'TEL DO REVENDEDOR', 
                         TBLESTOQUE.INTQUANTIDADEENTRADA AS 'QNT ENTRADA', TBLESTOQUE.INTQUANTIDADEVENDIDA AS 'QUANTIDADE VENDIDA', 
                         TBLESTOQUE.FLTVALORVENDAUNITARIO AS 'VALOR VENDA UNTIARIO', TBLPRODUTO.STRNOME AS 'NOME DO PRODUTO', 
                         TBLREVENDEDOR.STRFAX AS 'FAX REVENDEDOR', (TBLESTOQUE.FLTVALORVENDAUNITARIO - TBLESTOQUE.FLTVALORCUSTOUNITARIO) as 'LUCRO_UNITARIO',
						 TBLESTOQUE.INTQUANTIDADEENTRADA - TBLESTOQUE.INTQUANTIDADEVENDIDA   as 'QUANTIDADE ESPECIFICO EM ESTOQUE',
						 round(((TBLESTOQUE.FLTVALORVENDAUNITARIO*100)/TBLESTOQUE.FLTVALORCUSTOUNITARIO)-100,0, 0) as 'PC LUCRO'
FROM TBLESTOQUE INNER JOIN
                         TBLPRODUTO ON TBLESTOQUE.ID_PRODUTO = TBLPRODUTO.ID_PRODUTO INNER JOIN
                         TBLREVENDEDOR ON TBLPRODUTO.ID_REVENDEDOR = TBLREVENDEDOR.ID_REVENDEDOR INNER JOIN
                         TBLTIPOPRODUTO ON TBLPRODUTO.ID_TIPOPRODUTO = TBLTIPOPRODUTO.ID_TIPOPRODUTO

SELECT
round(((TBLESTOQUE.FLTVALORVENDAUNITARIO*100)/TBLESTOQUE.FLTVALORCUSTOUNITARIO)-100,0, 0)
FROM TBLESTOQUE WHERE ID_PRODUTO = '7897723900075'

select * from tblRevendedor
